### ISSUE TITLE
AppImage and Binary from dpkg  crash on startup on Ubuntu 20.10

### ISSUE THREAD

**Issue by fermat2a** [Komet/MediaElch#1171]
**Describe the bug**
Medial Elch AppImages crashes on startup:

```
➜  fermat@omen ~/usr/mediaelch ./MediaElch_linux_2.8.4_2021-01-09_git-28805a9.AppImage
MediaElch 2021-01-09 17:17:36.006 DEBUG : Loading advanced settings from: FilePath("/home/fermat/.local/share/kvibes/MediaElch/advancedsettings.xml")
MediaElch 2021-01-09 17:17:36.006 WARN  : [AdvancedSettings] advancedsettings.xml not found at  "/home/fermat/.local/share/kvibes/MediaElch/advancedsettings.xml"
MediaElch 2021-01-09 17:17:36.007 DEBUG : Advanced settings:
    locale:                  German (Germany)
    debugLog:                false
    logFile:                 
    forceCache:              false
    stylesheet:              <bundled>
    sortTokens:              Der, Die, Das, The, Le, La, Les, Un, Une, Des
    movieFilters:            *.mkv, *.mk3d, *.avi, *.mpg, *.mpeg, *.mp4, *.m2ts, *.disc, *.m4v, *.strm, *.dat, *.flv, *.vob, *.ts, *.iso, *.ogg, *.ogm, *.rmvb, *.img, *.wmv, *.mov, *.divx, VIDEO_TS.IFO, *.webm, index.bdmv, *.wtv
    concertFilters:          *.mkv, *.mk3d, *.avi, *.mpg, *.mpeg, *.mp4, *.m2ts, *.disc, *.m4v, *.strm, *.dat, *.flv, *.vob, *.ts, *.iso, *.ogg, *.ogm, *.rmvb, *.img, *.wmv, *.mov, *.divx, VIDEO_TS.IFO, *.webm, index.bdmv, *.wtv
    tvShowFilters:           *.mkv, *.mk3d, *.avi, *.mpg, *.mpeg, *.mp4, *.m2ts, *.disc, *.m4v, *.strm, *.dat, *.flv, *.vob, *.ts, *.iso, *.ogg, *.ogm, *.rmvb, *.img, *.wmv, *.mov, *.divx, VIDEO_TS.IFO, *.webm, index.bdmv, *.wtv
    subtitleFilters:         *.idx, *.sub, *.srr, *.srt, *.ass, *.ttml
    genreMappings:           
    audioCodecMappings:      
        mpa1l3: mp3
        aac lc: aac
        mpa1l2: mp2
    videoCodecMappings:      
        avc: h264
        v_mpeg4/iso/avc: h264
    certificationMappings:   
    studioMappings:          
    countryMappings:         
    writeThumbUrlsToNfo:     true
    episodeThumb dimensions: 
        width:               400
        height:              300
    bookletCut:              2
    useFirstStudioOnly:      false
    exclude patterns:        

MediaElch 2021-01-09 17:17:36.069 DEBUG : [TMDb] Request setup from server
MediaElch 2021-01-09 17:17:36.110 DEBUG : [TMDb] Request setup from server
MediaElch 2021-01-09 17:17:36.119 INFO  : [TvScraper] Initializing "TMDb TV"
MediaElch 2021-01-09 17:17:36.120 INFO  : [TvScraper] Initializing "TheTvDb"
MediaElch 2021-01-09 17:17:36.122 INFO  : [TvScraper] Initializing "IMDb TV"
MediaElch 2021-01-09 17:17:36.122 INFO  : [TvScraper] Initializing "TVmaze"
MediaElch 2021-01-09 17:17:36.192 DEBUG : [TMDb] Request setup from server
MediaElch 2021-01-09 17:17:36.192 DEBUG : [TMDb] Request setup from server
MediaElch 2021-01-09 17:17:36.565 INFO  : [DownloadsWidget] Start scanning for imports/downloads. Start Timer.
MediaElch 2021-01-09 17:17:36.756 DEBUG : MediaElch version "2.8.4" starting up
MediaElch 2021-01-09 17:17:36.876 INFO  : Searching for updates
MediaElch 2021-01-09 17:17:36.880 INFO  : [DownloadsWidget] Scanning for imports/downloads took: 315 ms
MediaElch 2021-01-09 17:17:36.880 INFO  : [DownloadsWidget] Updating imports/downloads lists: 0 ms
MediaElch 2021-01-09 17:17:36.884 INFO  : [TvScraper] Initialized: "IMDb TV"
MediaElch 2021-01-09 17:17:36.891 DEBUG : [MovieFileSearcher] Movie directory is not readable, skipping: "/scratch/fermat/Filme"
MediaElch 2021-01-09 17:17:36.891 DEBUG : [MovieFileSearcher] Adding movie directory "/home/fermat/Videos/otrv/Filme.hd"
MediaElch 2021-01-09 17:17:36.891 DEBUG : [MovieFileSearcher] Adding movie directory "/home/fermat/Videos/otrv/Filme.hq"
MediaElch 2021-01-09 17:17:36.892 DEBUG : [MovieFileSearcher] Movie directory is not readable, skipping: "/home/fermat/scratch/Filme.Blueray"
MediaElch 2021-01-09 17:17:36.892 DEBUG : [TvShowFileSearcher] TV show directory is not readable, skipping: "/home/fermat/mnt/Data_1/Video/blueray/Serien"
MediaElch 2021-01-09 17:17:36.892 DEBUG : [TvShowFileSearcher] Adding TV show directory "/home/fermat/Videos/otrv/Serien.hd"
MediaElch 2021-01-09 17:17:36.892 DEBUG : [ConcertFileSearcher] Concert directory is not redable, skipping: "/home/fermat/Videos/otrv/Konzerte.hq"
MediaElch 2021-01-09 17:17:36.903 DEBUG : [TMDb] Base url: "http://image.tmdb.org/t/p/"
MediaElch 2021-01-09 17:17:36.903 DEBUG : TMDb base url: "http://image.tmdb.org/t/p/"
MediaElch 2021-01-09 17:17:36.903 INFO  : [TvScraper] Initialized: "TMDb TV"
MediaElch 2021-01-09 17:17:36.903 DEBUG : [TMDb] Base url: "http://image.tmdb.org/t/p/"
[1]    274383 abort (core dumped)  ./MediaElch_linux_2.8.4_2021-01-09_git-28805a9.AppImage
➜  fermat@omen ~/usr/mediaelch
```

Using de debian package I also get a crash:

```
➜  fermat@omen ~ MediaElch
MediaElch 2021-01-09 17:24:23.751 DEBUG : Loading advanced settings from: FilePath("/home/fermat/.local/share/kvibes/MediaElch/advancedsettings.xml")
MediaElch 2021-01-09 17:24:23.752 WARN  : [AdvancedSettings] advancedsettings.xml not found at  "/home/fermat/.local/share/kvibes/MediaElch/advancedsettings.xml"
MediaElch 2021-01-09 17:24:23.752 DEBUG : Advanced settings:
    locale:                  German
    debugLog:                false
    logFile:                 
    forceCache:              false
    sortTokens:              Der, Die, Das, The, Le, La, Les, Un, Une, Des
    movieFilters:            *.mkv, *.mk3d, *.avi, *.mpg, *.mpeg, *.mp4, *.m2ts, *.disc, *.m4v, *.strm, *.dat, *.flv, *.vob, *.ts, *.iso, *.ogg, *.ogm, *.rmvb, *.img, *.wmv, *.mov, *.divx, VIDEO_TS.IFO, index.bdmv, *.wtv
    concertFilters:          *.mkv, *.mk3d, *.avi, *.mpg, *.mpeg, *.mp4, *.m2ts, *.disc, *.m4v, *.strm, *.dat, *.flv, *.vob, *.ts, *.iso, *.ogg, *.ogm, *.rmvb, *.img, *.wmv, *.mov, *.divx, VIDEO_TS.IFO, index.bdmv, *.wtv
    tvShowFilters:           *.mkv, *.mk3d, *.avi, *.mpg, *.mpeg, *.mp4, *.m2ts, *.disc, *.m4v, *.strm, *.dat, *.flv, *.vob, *.ts, *.iso, *.ogg, *.ogm, *.rmvb, *.img, *.wmv, *.mov, *.divx, VIDEO_TS.IFO, index.bdmv, *.wtv
    subtitleFilters:         *.idx, *.sub, *.srr, *.srt, *.ass, *.ttml
    genreMappings:           
    audioCodecMappings:      
        mpa1l3: mp3
        aac lc: aac
        mpa1l2: mp2
    videoCodecMappings:      
        v_mpeg4/iso/avc: h264
        avc: h264
    certificationMappings:   
    studioMappings:          
    countryMappings:         
    writeThumbUrlsToNfo:     true
    episodeThumb dimensions: 
        width:               400
        height:              300
    bookletCut:              2
    useFirstStudioOnly:      false
    exclude patterns:        

MediaElch 2021-01-09 17:24:23.788 DEBUG : [TMDb] Request setup from server
MediaElch 2021-01-09 17:24:23.793 DEBUG : [TMDb] Request setup from server
MediaElch 2021-01-09 17:24:23.841 DEBUG : [TMDb] Request setup from server
MediaElch 2021-01-09 17:24:23.842 DEBUG : [TMDb] Request setup from server
MediaElch 2021-01-09 17:24:23.914 DEBUG : Entered
MediaElch 2021-01-09 17:24:23.915 DEBUG : Entered
MediaElch 2021-01-09 17:24:23.996 DEBUG : Entered
MediaElch 2021-01-09 17:24:23.997 DEBUG : Entered, enabled= false
MediaElch 2021-01-09 17:24:24.037 DEBUG : Entered
MediaElch 2021-01-09 17:24:24.114 DEBUG : Entered
MediaElch 2021-01-09 17:24:24.127 DEBUG : Entered
MediaElch 2021-01-09 17:24:24.127 DEBUG : Entered
MediaElch 2021-01-09 17:24:24.175 INFO  : [DownloadsWidget] Start scanning for imports/downloads. Start Timer.
MediaElch 2021-01-09 17:24:24.290 DEBUG : MediaElch version "2.6.6" starting up
MediaElch 2021-01-09 17:24:24.357 DEBUG : Entered
MediaElch 2021-01-09 17:24:24.413 INFO  : Searching for updates
MediaElch 2021-01-09 17:24:24.417 INFO  : [DownloadsWidget] Scanning for imports/downloads took: 241 ms
MediaElch 2021-01-09 17:24:24.417 INFO  : [DownloadsWidget] Updating imports/downloads lists: 0 ms
MediaElch 2021-01-09 17:24:24.424 DEBUG : [MovieFileSearcher] Movie directory is not redable, skipping: "/scratch/fermat/Filme"
MediaElch 2021-01-09 17:24:24.424 DEBUG : [MovieFileSearcher] Adding movie directory "/home/fermat/Videos/otrv/Filme.hd"
MediaElch 2021-01-09 17:24:24.424 DEBUG : [MovieFileSearcher] Adding movie directory "/home/fermat/Videos/otrv/Filme.hq"
MediaElch 2021-01-09 17:24:24.424 DEBUG : [MovieFileSearcher] Movie directory is not redable, skipping: "/home/fermat/scratch/Filme.Blueray"
MediaElch 2021-01-09 17:24:24.425 DEBUG : [TvShowFileSearcher] TV show directory is not readable, skipping: "/home/fermat/mnt/Data_1/Video/blueray/Serien"
MediaElch 2021-01-09 17:24:24.425 DEBUG : [TvShowFileSearcher] Adding TV show directory "/home/fermat/Videos/otrv/Serien.hd"
MediaElch 2021-01-09 17:24:24.425 DEBUG : [ConcertFileSearcher] Concert directory is not redable, skipping: "/home/fermat/Videos/otrv/Konzerte.hq"
[1]    275416 abort (core dumped)  MediaElch
➜  fermat@omen ~
```

**To Reproduce**
4. See error / Crash

**Expected behavior**
Media Elche should start.

**Screenshots**
No GUI comes up

**MediaElch Version:**
 - [ ] 2.8.5-dev (nightly)
 - [x] 2.8.4 stable

**Operating System:**
 - [ ] Windows
 - [ ] macOS
 - [x] Linux (distribution: Ubuntu 20.04)

**Additional context**

Crash happens using AppImage and dpkg.

**Comment by bugwelle** [comment]
Does the AppImage of v2.8.2 work? :-)
If yes, then there's a regression on our side. If it does not, then there may be an issue in our AppImage handling.

**Comment by fermat2a** [comment]
Hi, same problem with AppImage of 2.8.2 and dpkg version of 2.8.4

**Comment by fermat2a** [comment]
I see for a short time a Window with a Subwindow of the scrapper. Then it crashes. Can you tell me where mediaelch stores its config (e.g. pathes to scan)? I would like to delete it and try again.

**Comment by fermat2a** [comment]
[_usr_bin_MediaElch.1000.crash.gz](https://github.com/Komet/MediaElch/files/5791451/_usr_bin_MediaElch.1000.crash.gz)

**Comment by fermat2a** [comment]
I have build the master successfully, but starting MediaElch ends up with the same crash. So I started it in gdb. Here I get following error:

```
Thread 1 "MediaElch" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
49	../sysdeps/unix/sysv/linux/raise.c: Datei oder Verzeichnis nicht gefunden.
(gdb)
```

Here the full backtrace:

```
(gdb) backtrace -full
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
        set = 
            {__val = {0, 4294967299, 140737488335192, 140737488335200, 93825007544672, 140737326062368, 4398046517247, 140737324329120, 0, 36902359007237, 7, 0, 10, 140737488335104, 1610213136, 134322565}}
        pid = <optimized out>
        tid = <optimized out>
#1  0x00007ffff5c42864 in __GI_abort () at abort.c:79
        save_stage = 1
        act = 
          {__sigaction_handler = {sa_handler = 0x5555573c25d0, sa_sigaction = 0x5555573c25d0}, sa_mask = {__val = {9458062191089461760, 433, 93825032639640, 93825024140880, 140737321954061, 3, 140737152842056, 140737488335600, 140737324010695, 140737488335520, 93825007631040, 140737152841520, 9458062191089461760, 93825004618448, 3, 140737488335600}}, sa_flags = -19744, sa_restorer = 0x7fffffffb2e8}
        sigs = {__val = {32, 0, 140737152841520, 9458062191089461760, 8388608, 1, 140737318487520, 140737321463621, 8, 500, 8, 140737321463825, 434, 93825032639640, 93825024140880, 140737321951901}}
#2  0x00005555555de5bf in mediaelch::messageHandler(QtMsgType, QMessageLogContext const&, QString const&) [clone .cold] ()
#3  0x00007ffff60c3488 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007ffff60c35a9 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007ffff6090b8a in QMessageLogger::fatal(char const*, ...) const () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007ffff7f4641b in  () at /usr/lib/x86_64-linux-gnu/libQt5QuickWidgets.so.5
#7  0x00007ffff7f46742 in  () at /usr/lib/x86_64-linux-gnu/libQt5QuickWidgets.so.5
#8  0x00007ffff7f48de5 in QQuickWidget::resizeEvent(QResizeEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5QuickWidgets.so.5
#9  0x00007ffff7a4ad64 in QWidget::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#10 0x00007ffff7a09013 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007ffff62ad1ca in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007ffff7a4255e in QWidgetPrivate::sendPendingMoveAndResizeEvents(bool, bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007ffff7a424bd in QWidgetPrivate::sendPendingMoveAndResizeEvents(bool, bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007ffff7a424bd in QWidgetPrivate::sendPendingMoveAndResizeEvents(bool, bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ffff7a424bd in QWidgetPrivate::sendPendingMoveAndResizeEvents(bool, bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007ffff7a424bd in QWidgetPrivate::sendPendingMoveAndResizeEvents(bool, bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007ffff7a424bd in QWidgetPrivate::sendPendingMoveAndResizeEvents(bool, bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007ffff7a424bd in QWidgetPrivate::sendPendingMoveAndResizeEvents(bool, bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007ffff7a424bd in QWidgetPrivate::sendPendingMoveAndResizeEvents(bool, bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007ffff7a424bd in QWidgetPrivate::sendPendingMoveAndResizeEvents(bool, bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007ffff7a424bd in QWidgetPrivate::sendPendingMoveAndResizeEvents(bool, bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007ffff7a424bd in QWidgetPrivate::sendPendingMoveAndResizeEvents(bool, bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007ffff7a424bd in QWidgetPrivate::sendPendingMoveAndResizeEvents(bool, bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007ffff7a424bd in QWidgetPrivate::sendPendingMoveAndResizeEvents(bool, bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#25 0x00007ffff7a424bd in QWidgetPrivate::sendPendingMoveAndResizeEvents(bool, bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#26 0x00007ffff7a424bd in QWidgetPrivate::sendPendingMoveAndResizeEvents(bool, bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#27 0x00007ffff7a424bd in QWidgetPrivate::sendPendingMoveAndResizeEvents(bool, bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#28 0x00007ffff7a424bd in QWidgetPrivate::sendPendingMoveAndResizeEvents(bool, bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#29 0x00007ffff7a46fcb in QWidgetPrivate::prepareToRender(QRegion const&, QFlags<QWidget::RenderFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#30 0x00007ffff7a47688 in QWidget::render(QPainter*, QPoint const&, QRegion const&, QFlags<QWidget::RenderFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#31 0x00007ffff7a47c5b in QWidget::render(QPaintDevice*, QPoint const&, QRegion const&, QFlags<QWidget::RenderFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#32 0x00007ffff7a47e8d in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#33 0x00007ffff7d9e8e2 in QGraphicsEffectSource::pixmap(Qt::CoordinateSystem, QPoint*, QGraphicsEffect::PixmapPadMode) const () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#34 0x00007ffff7d9ea8d in QGraphicsEffect::sourcePixmap(Qt::CoordinateSystem, QPoint*, QGraphicsEffect::PixmapPadMode) const () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#35 0x00007ffff7d9eed0 in QGraphicsDropShadowEffect::draw(QPainter*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#36 0x00007ffff7a43893 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#37 0x00007ffff7a441e3 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#38 0x00007ffff7a42b9c in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#39 0x00007ffff7a441e3 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#40 0x00007ffff7a42b9c in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#41 0x00007ffff7a441e3 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#42 0x00007ffff7a44002 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#43 0x00007ffff7a42b9c in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#44 0x00007ffff7a441e3 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#45 0x00007ffff7a42b9c in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#46 0x00007ffff7a19f7a in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#47 0x00007ffff7a1a7a7 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#48 0x00007ffff7a65f48 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#49 0x00007ffff7a09013 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#50 0x00007ffff62ad1ca in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#51 0x00007ffff6cce9a1 in QGuiApplicationPrivate::processExposeEvent(QWindowSystemInterfacePrivate::ExposeEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#52 0x00007ffff6ca32bb in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#53 0x00007ffff215935e in  () at /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#54 0x00007ffff50094db in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#55 0x00007ffff5009788 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#56 0x00007ffff5009853 in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#57 0x00007ffff63048b0 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#58 0x00005555557427a4 in FileScannerDialog::onStartMovieScanner() ()
#59 0x0000555555742d85 in FileScannerDialog::exec() ()
#60 0x00007ffff62d9651 in QObject::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#61 0x00007ffff7a09013 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#62 0x00007ffff62ad1ca in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#63 0x00007ffff62afbc1 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#64 0x00007ffff63051c7 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#65 0x00007ffff50094db in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#66 0x00007ffff5009788 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#67 0x00007ffff5009853 in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#68 0x00007ffff6304843 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#69 0x00007ffff62aba4b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#70 0x00007ffff62b3fc6 in QCoreApplication::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#71 0x0000555555617a5b in main ()
```

**Comment by jaumeramos** [comment]
Can confirm this bug is still happening in Ubuntu 20.04.
Tried latest builds without success, but even a previous appimage that was working for me (2.6.2) has stopped working after some ubuntu upgrade.
Tried to build from source without any problem but the same behavior. A shor appearance of a window and the sistem crashes. 
If running on gdb a window appears
Can provide further information if anyone needs it
![Selecció_853](https://user-images.githubusercontent.com/17320491/147464409-7d69b33e-5067-4bc1-a5f1-10729981d0e2.png)
[MediaElch crash.txt](https://github.com/Komet/MediaElch/files/7779828/MediaElch.crash.txt)
.

**Comment by bugwelle** [comment]
That's super strange... :/

> Tried to build from source without any problem but the same behavior.

Oh, so this is unrelated to the AppImage? I also work ob Kubuntu (20.04) and never had issues there.
If you have time, could you provide further debug traces (with GDB, etc.)?

Regards,
Andre

**Comment by jaumeramos** [comment]
> That's super strange... :/

Yes right, strange enough!! I've just launched with gdb the program built last day and now it's working OK.

No apt upgrade in between, just a couple of reboots. At the moment I'm using the build and I've been unable to find any glitch.

I've tried also the latest linux AppImage (2.8.12) and is working without any problem. The same file was crashing some days ago, it's why I tried to compile from source.

I'll keep on testing and if It crashes again will try to provide a full stacktrace.

Thanks four your support!

**Comment by bugwelle** [comment]
Thank you very much for your reply! And sorry about the delayed answer. :)

It may be that they've updated some packages and the issue went away, though that shouldn't interfere with the AppImage (at least in theory, I'd think).

I've tested the latest AppImage + AppImage of the latest release on Ubuntu 20.04 and it works as expected.

**Comment by bugwelle** [comment]
Tested again on Ubuntu 20.10, latest updates installed.

If anyone experiences issues again, please let me know. I will need the details from "About" -> "Developer".
