### ISSUE TITLE
MediaElch Coridian reliably crashes when scraping 10+ movies

### ISSUE THREAD

**Issue by zacharyfreeman70** [Komet/MediaElch#1408]
**Describe the bug**
I have a folder of several hundred ripped movies I need to create NFOs for. I point MediaElch to the relevant directory and it correctly detects each unscraped movie. When I highlight a group larger than 10, 11, 12, or 13 movies (it seems to vary, but it's always at least 10) and right-click and go to "Load Information" then proceed with the default configuration, a bunch of blue progress bars (appears to be one per movie) show up in the top right hand side of my screen, then the program crashes.

**To Reproduce**
1. Start MediaElch
2. Specify directory to scan.
3. Shift-click to highlight 10 or more movies.
4. Right-click group and select "Load Information"
5. On the "Movie Multi Scrape" dialogbox, Scraper: is set to "The Movie DB". Under "Infos to load" everything is checked except Tags. Automatically save each movie after scraping is unchecked. Update only movies with IMDb ID/TMDb Id is unchecked. 
6. Click "Start Scraping"
7. Program gets half-way through scrape and then freezes (Windows says program is not responding). User is then forced to kill the application.

**Expected behavior**
MediaElch should not crash when scraping a handful of images.

**Screenshots**

**MediaElch Version:**
 - [ ] 2.8.15-dev (nightly)
 - [x] 2.8.14 stable

**Operating System:**
 - [x] Windows
 - [ ] macOS
 - [ ] Linux (distribution: _._)

**Additional context**
It honestly seems like something is broken with whatever's handling the paralellism/threading of either accessing the data or saving the data. I'm able to scan movies 1-by-1, but for hundreds of movies, that will take forever. For what it's worth I have a slow internet connection *and* slow storage speed, so maybe there's a race condition here as well.

**Comment by bugwelle** [comment]
Thank you very much for reporting this issue. I will try to reproduce and then fix this issue.

**Comment by bugwelle** [comment]
Reproduced on Linux as well:

```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==7091==ERROR: AddressSanitizer: SEGV on unknown address (pc 0x7f6f057758a0 bp 0x7ffed4413c90 sp 0x7ffed4413a60 T0)
==7091==The signal is caused by a READ memory access.
==7091==Hint: this fault was caused by a dereference of a high value address (see register values below).  Dissassemble the provided pc to learn which register was used.
    #0 0x7f6f057758a0 in std::__atomic_base<int>::load(std::memory_order) const /opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/bits/atomic_base.h:396
    #1 0x7f6f057758a0 in int QAtomicOps<int>::loadRelaxed<int>(std::atomic<int> const&) ../../include/QtCore/../../src/corelib/thread/qatomic_cxx11.h:239
    #2 0x7f6f057758a0 in QBasicAtomicInteger<int>::loadRelaxed() const ../../include/QtCore/../../src/corelib/thread/qbasicatomic.h:107
    #3 0x7f6f057758a0 in QtPrivate::RefCount::deref() ../../include/QtCore/../../src/corelib/tools/qrefcount.h:66
    #4 0x7f6f057758a0 in QByteArray::operator=(QByteArray const&) text/qbytearray.cpp:1215
    #5 0x55b2d6637fc4 in MovieController::onDownloadFinished(DownloadManagerElement) ../MediaElch/src/movies/MovieController.cpp:365
    #6 0x55b2d663d041 in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<DownloadManagerElement>, void, void (MovieController::*)(DownloadManagerElement)>::call(void (MovieController::*)(DownloadManagerElement), MovieController*, void**) /home/andre/Qt/5.15.2/gcc_64/include/QtCore/qobjectdefs_impl.h:152
    #7 0x55b2d663cb22 in void QtPrivate::FunctionPointer<void (MovieController::*)(DownloadManagerElement)>::call<QtPrivate::List<DownloadManagerElement>, void>(void (MovieController::*)(DownloadManagerElement), MovieController*, void**) /home/andre/Qt/5.15.2/gcc_64/include/QtCore/qobjectdefs_impl.h:185
    #8 0x55b2d663bdd9 in QtPrivate::QSlotObject<void (MovieController::*)(DownloadManagerElement), QtPrivate::List<DownloadManagerElement>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) /home/andre/Qt/5.15.2/gcc_64/include/QtCore/qobjectdefs_impl.h:418
    #9 0x7f6f05925da2 in QObject::event(QEvent*) kernel/qobject.cpp:1314
    #10 0x7f6f0866943b in QApplicationPrivate::notify_helper(QObject*, QEvent*) kernel/qapplication.cpp:3632
    #11 0x7f6f0866ff1f in QApplication::notify(QObject*, QEvent*) kernel/qapplication.cpp:3378
    #12 0x7f6f058f6807 in QCoreApplication::notifyInternal2(QObject*, QEvent*) kernel/qcoreapplication.cpp:1063
    #13 0x7f6f058f9881 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) kernel/qcoreapplication.cpp:1817
    #14 0x7f6f05952b32 in postEventSourceDispatch kernel/qeventdispatcher_glib.cpp:277
    #15 0x7f6f04b4317c in g_main_context_dispatch (/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x5217c)
    #16 0x7f6f04b433ff  (/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x523ff)
    #17 0x7f6f04b434a2 in g_main_context_iteration (/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x524a2)
    #18 0x7f6f059521cb in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) kernel/qeventdispatcher_glib.cpp:423
    #19 0x7f6f058f5219 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) kernel/qeventloop.cpp:232
    #20 0x7f6f08851ff6 in QDialog::exec() dialogs/qdialog.cpp:601
    #21 0x55b2d666b6f0 in MovieMultiScrapeDialog::exec() ../MediaElch/src/ui/movies/MovieMultiScrapeDialog.cpp:100
    #22 0x55b2d6651b20 in MovieFilesWidget::multiScrape() ../MediaElch/src/ui/movies/MovieFilesWidget.cpp:186
    #23 0x55b2d6507e98 in MainWindow::onActionSearch() ../MediaElch/src/ui/main/MainWindow.cpp:393
    #24 0x55b2d6534b2b in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (MainWindow::*)()>::call(void (MainWindow::*)(), MainWindow*, void**) (/home/andre/Projects/Private/build-MediaElch-Desktop_Qt_5_15_2_GCC_64bit-Debug/MediaElch+0x1015b2b)
    #25 0x55b2d6532f8e in void QtPrivate::FunctionPointer<void (MainWindow::*)()>::call<QtPrivate::List<>, void>(void (MainWindow::*)(), MainWindow*, void**) (/home/andre/Projects/Private/build-MediaElch-Desktop_Qt_5_15_2_GCC_64bit-Debug/MediaElch+0x1013f8e)
    #26 0x55b2d652fe1f in QtPrivate::QSlotObject<void (MainWindow::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (/home/andre/Projects/Private/build-MediaElch-Desktop_Qt_5_15_2_GCC_64bit-Debug/MediaElch+0x1010e1f)
    #27 0x7f6f0592ef2f in QtPrivate::QSlotObjectBase::call(QObject*, void**) ../../include/QtCore/../../src/corelib/kernel/qobjectdefs_impl.h:398
    #28 0x7f6f0592ef2f in void doActivate<false>(QObject*, int, void**) kernel/qobject.cpp:3886
    #29 0x55b2d6d1452a in Navbar::sigSearch() /home/andre/Projects/Private/build-MediaElch-Desktop_Qt_5_15_2_GCC_64bit-Debug/moc_Navbar.cpp:290
    #30 0x55b2d655ab64 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (Navbar::*)()>::call(void (Navbar::*)(), Navbar*, void**) /home/andre/Qt/5.15.2/gcc_64/include/QtCore/qobjectdefs_impl.h:152
    #31 0x55b2d655a8f4 in void QtPrivate::FunctionPointer<void (Navbar::*)()>::call<QtPrivate::List<>, void>(void (Navbar::*)(), Navbar*, void**) /home/andre/Qt/5.15.2/gcc_64/include/QtCore/qobjectdefs_impl.h:185
    #32 0x55b2d655a3bb in QtPrivate::QSlotObject<void (Navbar::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) /home/andre/Qt/5.15.2/gcc_64/include/QtCore/qobjectdefs_impl.h:418
    #33 0x7f6f0592ef2f in QtPrivate::QSlotObjectBase::call(QObject*, void**) ../../include/QtCore/../../src/corelib/kernel/qobjectdefs_impl.h:398
    #34 0x7f6f0592ef2f in void doActivate<false>(QObject*, int, void**) kernel/qobject.cpp:3886
    #35 0x7f6f08754ba1 in QAbstractButton::clicked(bool) .moc/moc_qabstractbutton.cpp:308
    #36 0x7f6f08754da9 in QAbstractButtonPrivate::emitClicked() widgets/qabstractbutton.cpp:415
    #37 0x7f6f08756a2e in QAbstractButtonPrivate::click() widgets/qabstractbutton.cpp:408
    #38 0x7f6f08756b94 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) widgets/qabstractbutton.cpp:1044
    #39 0x7f6f08839a89 in QToolButton::mouseReleaseEvent(QMouseEvent*) widgets/qtoolbutton.cpp:622
    #40 0x7f6f086a773f in QWidget::event(QEvent*) kernel/qwidget.cpp:9019
    #41 0x7f6f08839b58 in QToolButton::event(QEvent*) widgets/qtoolbutton.cpp:1012
    #42 0x7f6f0866943b in QApplicationPrivate::notify_helper(QObject*, QEvent*) kernel/qapplication.cpp:3632
    #43 0x7f6f086701f7 in QApplication::notify(QObject*, QEvent*) kernel/qapplication.cpp:3076
    #44 0x7f6f058f6807 in QCoreApplication::notifyInternal2(QObject*, QEvent*) kernel/qcoreapplication.cpp:1063
    #45 0x7f6f0866f539 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) kernel/qapplication.cpp:2614
    #46 0x7f6f086c0fe7 in QWidgetWindow::handleMouseEvent(QMouseEvent*) kernel/qwidgetwindow.cpp:684
    #47 0x7f6f086c3cf2 in QWidgetWindow::event(QEvent*) kernel/qwidgetwindow.cpp:300
    #48 0x7f6f0866943b in QApplicationPrivate::notify_helper(QObject*, QEvent*) kernel/qapplication.cpp:3632
    #49 0x7f6f0866ff1f in QApplication::notify(QObject*, QEvent*) kernel/qapplication.cpp:3378
    #50 0x7f6f058f6807 in QCoreApplication::notifyInternal2(QObject*, QEvent*) kernel/qcoreapplication.cpp:1063
    #51 0x7f6f072fa56c in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) kernel/qguiapplication.cpp:2282
    #52 0x7f6f072fb954 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) kernel/qguiapplication.cpp:2002
    #53 0x7f6f072d78aa in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) kernel/qwindowsysteminterface.cpp:1169
    #54 0x7f6efd044699 in xcbSourceDispatch /home/qt/work/qt/qtbase/src/plugins/platforms/xcb/qxcbeventdispatcher.cpp:105
    #55 0x7f6f04b4317c in g_main_context_dispatch (/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x5217c)
    #56 0x7f6f04b433ff  (/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x523ff)
    #57 0x7f6f04b434a2 in g_main_context_iteration (/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x524a2)
    #58 0x7f6f059521cb in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) kernel/qeventdispatcher_glib.cpp:423
    #59 0x7f6f058f5219 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) kernel/qeventloop.cpp:232
    #60 0x7f6f058fe1d2 in QCoreApplication::exec() kernel/qcoreapplication.cpp:1371
    #61 0x55b2d60da475 in main ../MediaElch/src/main.cpp:134
    #62 0x7f6f0505d0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #63 0x55b2d607b42d in _start (/home/andre/Projects/Private/build-MediaElch-Desktop_Qt_5_15_2_GCC_64bit-Debug/MediaElch+0xb5c42d)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/bits/atomic_base.h:396 in std::__atomic_base<int>::load(std::memory_order) const
==7091==ABORTING
```

**Comment by bugwelle** [comment]
Found the issue:

If downloads were aborted, the still emitted the "finished" event which lead to the "downloads left" counter being below zero. After fixing this, MediaElch no longer crashes. However, the issue in #1409 still persists. But I now know where to look.

Thank you very much!

**Comment by zacharyfreeman70** [comment]
Just downloaded the newest 2.8.16 release to test this fix. It works! Thank you for taking a look.

In my opinion, MediaElch continues to offer the best/cleanest user experience out of all the media managers out there, and that great user experience extends all the way back to the developers working on it.

Please keep up the awesome work, @bugwelle!

**Comment by bugwelle** [comment]
Thanks! Glad it works. If you find any other bugs, please let me know.
